# Generated by Django 3.2.7 on 2021-09-11 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('会場', '会場'), ('オンライン', 'オンライン')], max_length=10)),
                ('affiliation', models.CharField(choices=[('防水', '防水'), ('床', '床'), ('住建', '住建'), ('複合', '複合')], max_length=5)),
                ('staff', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_application_date', models.DateField(null=True)),
                ('end_application_date', models.DateField(null=True)),
                ('number_of_attendees', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(null=True)),
                ('application_page', models.URLField()),
                ('application_list', models.URLField()),
                ('autience_page', models.URLField()),
                ('event_page', models.URLField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('invitation_mail', models.DateField(null=True)),
                ('remaind_mail', models.DateField(null=True)),
                ('viewing_guide_mail', models.DateField(null=True)),
                ('thank_you_mail', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
