# Generated by Django 3.2.7 on 2021-09-28 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='セミナー名')),
                ('method', models.CharField(choices=[('会場', '会場'), ('オンライン', 'オンライン')], max_length=10, verbose_name='開催方法')),
                ('affiliation', models.CharField(choices=[('防水', '防水'), ('床', '床'), ('住建', '住建'), ('複合', '複合')], max_length=5, verbose_name='所属')),
                ('staff', models.CharField(max_length=50, verbose_name='担当者')),
                ('place', models.CharField(max_length=255, verbose_name='場所')),
                ('start_date', models.DateField(verbose_name='開催日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('start_application_date', models.DateField(blank=True, null=True, verbose_name='申込開始日')),
                ('end_application_date', models.DateField(blank=True, null=True, verbose_name='申込締切日')),
                ('number_of_attendees', models.IntegerField(default=0, verbose_name='出席者')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='定員')),
                ('application_page', models.URLField(blank=True, null=True, verbose_name='申込ページ')),
                ('application_list', models.URLField(blank=True, null=True, verbose_name='申込者一覧')),
                ('audience_page', models.URLField(blank=True, null=True, verbose_name='視聴ページ')),
                ('event_page', models.URLField(blank=True, verbose_name='イベントページ')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='ZOOM予約')),
                ('invitation_mail', models.DateField(blank=True, verbose_name='招待メール配信日')),
                ('remaind_mail', models.DateField(blank=True, verbose_name='リマインドメール配信日')),
                ('viewing_guide_mail', models.DateField(blank=True, verbose_name='視聴案内メール配信日')),
                ('thank_you_mail', models.DateField(blank=True, verbose_name='御礼メール配信日')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新日')),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
