# Generated by Django 3.2.7 on 2021-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='application_list',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='application_page',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='autience_page',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='event_page',
            field=models.URLField(blank=True),
        ),
    ]
