# Generated by Django 3.2.7 on 2021-09-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='application_list',
            field=models.URLField(blank=True, default=1, verbose_name='申込者一覧'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='application_page',
            field=models.URLField(blank=True, default=2, verbose_name='申込ページ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='audience_page',
            field=models.URLField(blank=True, verbose_name='視聴ページ'),
        ),
    ]
