# Generated by Django 3.2.7 on 2021-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_auto_20210929_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='invitation_mail',
            field=models.DateField(blank=True, null=True, verbose_name='招待メール配信日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='remaind_mail',
            field=models.DateField(blank=True, null=True, verbose_name='リマインドメール配信日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='thank_you_mail',
            field=models.DateField(blank=True, null=True, verbose_name='御礼メール配信日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='viewing_guide_mail',
            field=models.DateField(blank=True, null=True, verbose_name='視聴案内メール配信日'),
        ),
    ]
