# Generated by Django 3.2.7 on 2021-09-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_auto_20210911_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='autience_page',
        ),
        migrations.AddField(
            model_name='seminar',
            name='audience_page',
            field=models.URLField(blank=True, verbose_name='視聴ページ'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='affiliation',
            field=models.CharField(choices=[('防水', '防水'), ('床', '床'), ('住建', '住建'), ('複合', '複合')], max_length=5, verbose_name='所属'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='application_list',
            field=models.URLField(blank=True, verbose_name='申込者一覧'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='application_page',
            field=models.URLField(blank=True, verbose_name='申込ページ'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='capacity',
            field=models.IntegerField(null=True, verbose_name='定員'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='end_application_date',
            field=models.DateField(null=True, verbose_name='申込締切日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='end_date',
            field=models.DateField(verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='event_page',
            field=models.URLField(blank=True, verbose_name='イベントページ'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='invitation_mail',
            field=models.DateField(null=True, verbose_name='招待メール配信日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='is_reserved',
            field=models.BooleanField(default=False, verbose_name='ZOOM予約'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='method',
            field=models.CharField(choices=[('会場', '会場'), ('オンライン', 'オンライン')], max_length=10, verbose_name='開催方法'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='name',
            field=models.CharField(max_length=255, verbose_name='セミナー名'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='number_of_attendees',
            field=models.IntegerField(default=0, verbose_name='出席者'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='place',
            field=models.CharField(max_length=255, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='remaind_mail',
            field=models.DateField(null=True, verbose_name='リマインドメール配信日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='staff',
            field=models.CharField(max_length=50, verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_application_date',
            field=models.DateField(null=True, verbose_name='申込開始日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='start_date',
            field=models.DateField(verbose_name='開催日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='thank_you_mail',
            field=models.DateField(null=True, verbose_name='御礼メール配信日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='viewing_guide_mail',
            field=models.DateField(null=True, verbose_name='視聴案内メール配信日'),
        ),
    ]
