# Generated by Django 3.2.7 on 2021-10-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_auto_20210929_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='department',
            field=models.CharField(default=1, max_length=50, verbose_name='部署'),
            preserve_default=False,
        ),
    ]
