# Generated by Django 3.2.7 on 2021-10-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0004_seminar_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='application_list',
            field=models.URLField(blank=True, null=True, verbose_name='申込者一覧'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='application_page',
            field=models.URLField(blank=True, null=True, verbose_name='申込ページ'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='audience_page',
            field=models.URLField(blank=True, null=True, verbose_name='視聴ページ'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='event_page',
            field=models.URLField(blank=True, null=True, verbose_name='イベントページ'),
        ),
    ]
