# Generated by Django 3.2.7 on 2021-10-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_auto_20211002_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='場所'),
        ),
    ]
