# Generated by Django 3.2.7 on 2021-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_alter_seminar_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='staff',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='担当者'),
        ),
    ]
